# Generated by Django 5.0.1 on 2025-11-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Short Answer'), ('textarea', 'Paragraph'), ('multiple_choice', 'Multiple Choice'), ('checkbox', 'Checkboxes'), ('dropdown', 'Dropdown'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('url', 'URL')], default='text', max_length=20),
        ),
    ]
