# Generated by Django 5.2.7 on 2025-11-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Short Answer'), ('textarea', 'Detailed Answer'), ('multiple_choice', 'Multiple Choice')], default='text', max_length=20),
        ),
    ]
