# Generated by Django 5.2.8 on 2025-11-19 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name', 'email'],
            },
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['response', 'question'], name='interviews__respons_cab15e_idx'),
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='interviews.candidate'),
        ),
        migrations.AddIndex(
            model_name='interviewresponse',
            index=models.Index(fields=['interview', 'submitted_at'], name='interviews__intervi_7b5aed_idx'),
        ),
    ]
